-- Exclui tabelas existentes para garantir uma recriação limpa (CUIDADO EM PRODUÇÃO)
DROP TABLE IF EXISTS "relatoriofiscal", "pendenciarelatorio", "arquivo", "contrato", "usuario", "contratado", "modalidade", "status", "perfil", "statusrelatorio", "statuspendencia";

-- Tabela de Perfis de Usuário
CREATE TABLE "perfil" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

-- Tabela de Status Gerais (para contratos)
CREATE TABLE "status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

-- Tabela de Modalidades de Contrato
CREATE TABLE "modalidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

-- Tabela de Usuários
CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "cpf" varchar(11) NOT NULL,
  "matricula" varchar(20),
  "senha" varchar(255) NOT NULL,
  "perfil_id" int NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("perfil_id") REFERENCES "perfil" ("id")
);

-- Tabela de Contratados
CREATE TABLE "contratado" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "cnpj" varchar(14),
  "cpf" varchar(11),
  "telefone" varchar(20),
  "email" varchar(255) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Tabela de Contratos
CREATE TABLE "contrato" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nr_contrato" varchar(50) NOT NULL,
  "objeto" text NOT NULL,
  "valor_anual" decimal(15,2),
  "valor_global" decimal(15,2),
  "base_legal" varchar(255),
  "data_inicio" date NOT NULL,
  "data_fim" date NOT NULL,
  "termos_contratuais" text,
  "contratado_id" int NOT NULL,
  "modalidade_id" int NOT NULL,
  "status_id" int NOT NULL DEFAULT 1,
  "gestor_id" int NOT NULL,
  "fiscal_id" int NOT NULL,
  "fiscal_substituto_id" int,
  "pae" varchar(50),
  "doe" varchar(50),
  "data_doe" date,
  "documento" integer,
  "ativo" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("contratado_id") REFERENCES "contratado" ("id"),
  FOREIGN KEY ("modalidade_id") REFERENCES "modalidade" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "status" ("id"),
  FOREIGN KEY ("gestor_id") REFERENCES "usuario" ("id"),
  FOREIGN KEY ("fiscal_id") REFERENCES "usuario" ("id"),
  FOREIGN KEY ("fiscal_substituto_id") REFERENCES "usuario" ("id")
);

-- Tabela de Arquivos
CREATE TABLE "arquivo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_arquivo" varchar(255) NOT NULL,
  "path_armazenamento" varchar(500) NOT NULL,
  "tipo_arquivo" text,
  "tamanho_bytes" int,
  "contrato_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("contrato_id") REFERENCES "contrato" ("id")
);

-- Tabela de Status das Pendências
CREATE TABLE "statuspendencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

-- Tabela de Pendências de Relatórios
CREATE TABLE "pendenciarelatorio" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contrato_id" int NOT NULL,
  "descricao" text NOT NULL,
  "data_prazo" date NOT NULL,
  "status_pendencia_id" int NOT NULL,
  "criado_por_usuario_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("contrato_id") REFERENCES "contrato" ("id"),
  FOREIGN KEY ("status_pendencia_id") REFERENCES "statuspendencia" ("id"),
  FOREIGN KEY ("criado_por_usuario_id") REFERENCES "usuario" ("id")
);

-- Tabela de Status dos Relatórios
CREATE TABLE "statusrelatorio" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true
);

-- Tabela de Relatórios Fiscais
CREATE TABLE "relatoriofiscal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contrato_id" int NOT NULL,
  "fiscal_usuario_id" int NOT NULL,
  "arquivo_id" int UNIQUE NOT NULL,
  "status_id" int NOT NULL,
  "mes_competencia" date NOT NULL,
  "observacoes_fiscal" text,
  "aprovador_usuario_id" int,
  "data_analise" timestamp,
  "observacoes_aprovador" text,
  "pendencia_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  FOREIGN KEY ("contrato_id") REFERENCES "contrato" ("id"),
  FOREIGN KEY ("fiscal_usuario_id") REFERENCES "usuario" ("id"),
  FOREIGN KEY ("aprovador_usuario_id") REFERENCES "usuario" ("id"),
  FOREIGN KEY ("arquivo_id") REFERENCES "arquivo" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "statusrelatorio" ("id"),
  FOREIGN KEY ("pendencia_id") REFERENCES "pendenciarelatorio" ("id")
);

-- --- ÍNDICES DE UNICIDADE PARCIAL (PARA SOFT DELETE) ---

-- Unicidade para registros ATIVOS
CREATE UNIQUE INDEX idx_unique_perfil_nome_ativo ON perfil (nome) WHERE ativo IS TRUE;
CREATE UNIQUE INDEX idx_unique_status_nome_ativo ON status (nome) WHERE ativo IS TRUE;
CREATE UNIQUE INDEX idx_unique_modalidade_nome_ativo ON modalidade (nome) WHERE ativo IS TRUE;
CREATE UNIQUE INDEX idx_unique_statuspendencia_nome_ativo ON statuspendencia (nome) WHERE ativo IS TRUE;
CREATE UNIQUE INDEX idx_unique_statusrelatorio_nome_ativo ON statusrelatorio (nome) WHERE ativo IS TRUE;

CREATE UNIQUE INDEX idx_unique_contratado_cnpj_ativo ON contratado (cnpj) WHERE ativo IS TRUE AND cnpj IS NOT NULL;
CREATE UNIQUE INDEX idx_unique_contratado_cpf_ativo ON contratado (cpf) WHERE ativo IS TRUE AND cpf IS NOT NULL;
CREATE UNIQUE INDEX idx_unique_contratado_email_ativo ON contratado (email) WHERE ativo IS TRUE;

CREATE UNIQUE INDEX idx_unique_usuario_email_ativo ON usuario (email) WHERE ativo IS TRUE;
CREATE UNIQUE INDEX idx_unique_usuario_cpf_ativo ON usuario (cpf) WHERE ativo IS TRUE;
CREATE UNIQUE INDEX idx_unique_usuario_matricula_ativo ON usuario (matricula) WHERE ativo IS TRUE AND matricula IS NOT NULL;

CREATE UNIQUE INDEX idx_unique_contrato_nr_contrato_ativo ON contrato (nr_contrato) WHERE ativo IS TRUE;