-- Tabela de Contratos
CREATE TABLE "contrato" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nr_contrato" varchar(50) UNIQUE NOT NULL,
  "objeto" text NOT NULL,
  "valor_anual" decimal(15,2),
  "valor_global" decimal(15,2),
  "base_legal" varchar(255),
  "data_inicio" date NOT NULL,
  "data_fim" date NOT NULL,
  "termos_contratuais" text,
  "contratado_id" int NOT NULL,
  "modalidade_id" int NOT NULL,
  "status_id" int NOT NULL DEFAULT 1,
  "gestor_id" int NOT NULL,
  "fiscal_id" int NOT NULL,
  "fiscal_substituto_id" int,
  "pae" varchar(50),
  "doe" varchar(50),
  "data_doe" date,
  "documento" integer,
  "ativo" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Tabela de Relatórios Fiscais
CREATE TABLE "relatoriofiscal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contrato_id" int NOT NULL,
  "fiscal_usuario_id" int NOT NULL,
  "arquivo_id" int UNIQUE NOT NULL,
  "status_id" int NOT NULL,
  "mes_competencia" date NOT NULL,
  "observacoes_fiscal" text,
  "aprovador_usuario_id" int,
  "data_analise" timestamp,
  "observacoes_aprovador" text,
  "pendencia_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Tabela de Status dos Relatórios
CREATE TABLE "statusrelatorio" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

-- Tabela de Status das Pendências
CREATE TABLE "statuspendencia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

-- Tabela de Pendências de Relatórios
CREATE TABLE "pendenciarelatorio" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contrato_id" int NOT NULL,
  "descricao" text NOT NULL,
  "data_prazo" date NOT NULL,
  "status_pendencia_id" int NOT NULL,
  "criado_por_usuario_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Tabela de Contratados
CREATE TABLE "contratado" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "cnpj" varchar(14) UNIQUE,
  "cpf" varchar(11) UNIQUE,
  "telefone" varchar(20),
  "email" varchar(255) UNIQUE NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Tabela de Modalidades de Contrato
CREATE TABLE "modalidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL
);

-- Tabela de Usuários
CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "matricula" varchar(20) UNIQUE,
  "senha" varchar(255) NOT NULL,
  "perfil_id" int NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Tabela de Perfis de Usuário
CREATE TABLE "perfil" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

-- Tabela de Status Gerais (para contratos)
CREATE TABLE "status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) UNIQUE NOT NULL
);

-- Tabela de Arquivos
CREATE TABLE "arquivo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_arquivo" varchar(255) NOT NULL,
  "path_armazenamento" varchar(500) NOT NULL,
  "tipo_arquivo" varchar(50),
  "tamanho_bytes" int,
  "contrato_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

-- Comentários das colunas
COMMENT ON COLUMN "relatoriofiscal"."contrato_id" IS 'Qual contrato este relatório pertence.';
COMMENT ON COLUMN "relatoriofiscal"."fiscal_usuario_id" IS 'Qual fiscal submeteu o relatório.';
COMMENT ON COLUMN "relatoriofiscal"."arquivo_id" IS 'O ID do arquivo que foi efetivamente enviado.';
COMMENT ON COLUMN "relatoriofiscal"."status_id" IS 'O status atual do relatório (Pendente, Aprovado, etc.).';
COMMENT ON COLUMN "relatoriofiscal"."mes_competencia" IS 'Mês/Ano a que o relatório se refere. Ex: 2025-07-01 para Jul/2025.';
COMMENT ON COLUMN "relatoriofiscal"."observacoes_fiscal" IS 'Comentários que o fiscal pode adicionar na submissão.';
COMMENT ON COLUMN "relatoriofiscal"."aprovador_usuario_id" IS 'Qual administrador analisou o relatório. Preenchido na aprovação/rejeição.';
COMMENT ON COLUMN "relatoriofiscal"."data_analise" IS 'Quando o relatório foi analisado.';
COMMENT ON COLUMN "relatoriofiscal"."observacoes_aprovador" IS 'Feedback do administrador, obrigatório em caso de rejeição.';
COMMENT ON COLUMN "relatoriofiscal"."pendencia_id" IS 'Se este relatório responde a uma pendência específica.';
COMMENT ON COLUMN "relatoriofiscal"."created_at" IS 'Data de submissão do relatório.';
COMMENT ON COLUMN "statusrelatorio"."nome" IS 'Ex: Pendente de Análise, Aprovado, Rejeitado com Pendência';
COMMENT ON COLUMN "statuspendencia"."nome" IS 'Ex: Pendente, Concluída, Cancelada';
COMMENT ON COLUMN "pendenciarelatorio"."contrato_id" IS 'A qual contrato esta pendência se refere.';
COMMENT ON COLUMN "pendenciarelatorio"."descricao" IS 'Descrição da pendência criada pelo Administrador. Ex: Relatório Semestral de Atividades.';
COMMENT ON COLUMN "pendenciarelatorio"."data_prazo" IS 'Data limite para o envio do relatório.';
COMMENT ON COLUMN "pendenciarelatorio"."status_pendencia_id" IS 'Status da pendência em si (Pendente, Concluída).';
COMMENT ON COLUMN "pendenciarelatorio"."criado_por_usuario_id" IS 'Qual Administrador criou a pendência.';
COMMENT ON COLUMN "usuario"."senha" IS 'Deve ser armazenada como hash';
COMMENT ON COLUMN "perfil"."nome" IS 'Ex: Administrador, Gestor, Fiscal';
COMMENT ON COLUMN "status"."nome" IS 'Ex: Vigente, Encerrado, Rescindido, Apostilado';
COMMENT ON COLUMN "arquivo"."contrato_id" IS 'Referência geral ao contrato principal para facilitar buscas.';

-- Definição das Chaves Estrangeiras (FOREIGN KEYS)
ALTER TABLE "relatoriofiscal" ADD FOREIGN KEY ("contrato_id") REFERENCES "contrato" ("id");
ALTER TABLE "relatoriofiscal" ADD FOREIGN KEY ("fiscal_usuario_id") REFERENCES "usuario" ("id");
ALTER TABLE "relatoriofiscal" ADD FOREIGN KEY ("aprovador_usuario_id") REFERENCES "usuario" ("id");
ALTER TABLE "relatoriofiscal" ADD FOREIGN KEY ("arquivo_id") REFERENCES "arquivo" ("id");
ALTER TABLE "relatoriofiscal" ADD FOREIGN KEY ("status_id") REFERENCES "statusrelatorio" ("id");
ALTER TABLE "contrato" ADD FOREIGN KEY ("contratado_id") REFERENCES "contratado" ("id");
ALTER TABLE "contrato" ADD FOREIGN KEY ("modalidade_id") REFERENCES "modalidade" ("id");
ALTER TABLE "contrato" ADD FOREIGN KEY ("status_id") REFERENCES "status" ("id");
ALTER TABLE "contrato" ADD FOREIGN KEY ("gestor_id") REFERENCES "usuario" ("id");
ALTER TABLE "contrato" ADD FOREIGN KEY ("fiscal_id") REFERENCES "usuario" ("id");
ALTER TABLE "contrato" ADD FOREIGN KEY ("fiscal_substituto_id") REFERENCES "usuario" ("id");
ALTER TABLE "usuario" ADD FOREIGN KEY ("perfil_id") REFERENCES "perfil" ("id");
ALTER TABLE "arquivo" ADD FOREIGN KEY ("contrato_id") REFERENCES "contrato" ("id");
ALTER TABLE "pendenciarelatorio" ADD FOREIGN KEY ("contrato_id") REFERENCES "contrato" ("id");
ALTER TABLE "pendenciarelatorio" ADD FOREIGN KEY ("status_pendencia_id") REFERENCES "statuspendencia" ("id");
ALTER TABLE "pendenciarelatorio" ADD FOREIGN KEY ("criado_por_usuario_id") REFERENCES "usuario" ("id");
ALTER TABLE "relatoriofiscal" ADD FOREIGN KEY ("pendencia_id") REFERENCES "pendenciarelatorio" ("id");
 